# Generated by Django 4.1.7 on 2023-04-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_rename_name_subject_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Subjects'},
        ),
    ]
