# Generated by Django 4.1.7 on 2023-04-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='hint_used',
            field=models.BooleanField(default=False, verbose_name='Hint Used'),
        ),
    ]
