# Generated by Django 4.1.7 on 2023-04-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated on'),
        ),
    ]
