# Generated by Django 4.1.7 on 2023-04-07 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers_portal', '0002_alter_course_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='overview',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=1, verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administration.subject', verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.CharField(blank=True, max_length=260, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField()),
                ('slug', models.CharField(blank=True, max_length=260, null=True, unique=True, verbose_name='Slug')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers_portal.course', verbose_name='Course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name_plural': 'Topics',
                'ordering': ['pk'],
            },
        ),
    ]
