# Generated by Django 4.1.7 on 2023-04-08 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers_portal', '0003_remove_course_overview_course_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('description', models.TextField()),
                ('slug', models.CharField(blank=True, max_length=260, null=True, unique=True, verbose_name='Slug')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers_portal.topic', verbose_name='Course')),
            ],
            options={
                'verbose_name_plural': 'Quizes',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('question_type', models.CharField(choices=[('text', 'text'), ('password', 'password'), ('number', 'number'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('date', 'date'), ('Drop Down', 'Drop Down')], max_length=35, verbose_name='Question Type')),
                ('slug', models.CharField(blank=True, max_length=260, null=True, unique=True, verbose_name='Slug')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers_portal.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name_plural': 'Quiz Questions',
                'ordering': ['pk'],
            },
        ),
    ]
