# Generated by Django 4.1.7 on 2023-04-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_portal', '0004_quiz_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='Is Required'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='ordering',
            field=models.CharField(default=1, max_length=10, verbose_name='Ordering Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('Drop Down', 'Drop Down')], max_length=35, verbose_name='Question Type'),
        ),
        migrations.CreateModel(
            name='QuestionChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_statement', models.CharField(max_length=250, verbose_name='Choice Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers_portal.quizquestion', verbose_name='Question')),
            ],
            options={
                'verbose_name_plural': 'Question Choices',
                'ordering': ['pk'],
            },
        ),
    ]
