# Generated by Django 4.1.7 on 2023-04-09 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_portal', '0005_quizquestion_is_required_quizquestion_ordering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionchoices',
            name='quiz',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='teachers_portal.quiz', verbose_name='Quiz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('text', 'text'), ('number', 'number'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('Drop Down', 'Drop Down'), ('Code', 'Code')], max_length=35, verbose_name='Question Type'),
        ),
    ]
