# Generated by Django 4.1.7 on 2023-04-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_portal', '0006_questionchoices_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Question Answer'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='hint_text',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Hint'),
        ),
    ]
