# Generated by Django 4.1.7 on 2023-05-03 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers_portal', '0008_remove_quizquestion_ordering_quiz_questions_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_students', models.ManyToManyField(related_name='teacher_enrollments', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_enrollment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
