# Generated by Django 4.1.7 on 2023-05-03 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_portal', '0009_teacherenrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherenrollment',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Teacher Enrollments'},
        ),
    ]
